export enum StaffDesignation {
  HOD = 'Head of Department',
  Dean = 'Dean',
  Professor = 'Professor',
  AssociateProfessor = 'Associate Professor',
  AssistantProfessor = 'Assistant Professor',
  Lecturer = 'Lecturer',
  TeachingAssistant = 'Teaching Assistant',
  ResearchAssistant = 'Research Assistant',
  AdminAssistant = 'Admin Assistant',
  NonTeaching = 'Non-Teaching Staff',
  Registrar = 'Registrar',
  ViceChancellor = 'Vice Chancellor',
  Director = 'Director',
  Chancellor = 'Chancellor',
  HallWarden = 'Hall Warden',
  Librarian = 'Librarian',
  SportsMaster = 'Sports Master',
}
